
print()
import time
print()
name=str(input("Digite  seu nome completo:")).strip()
time.sleep(1)
print("Analisando seu nome...")
time.sleep(1.5)
print("Seu nome em maiúsculas é {}".format(name.upper()))
time.sleep(1)
print("Seu nome em minúsculas é {}".format(name.lower()))
time.sleep(1)
print("Seu nome tem ao todo {} letras".format(len(name)-name.count(" ")))
time.sleep(1)
separa=name.split()
print("Seu primeiro nome é {} e ele tem {} letras".format(separa[0],len(separa[0]))) 
time.sleep(1)
print("Seu segundo nome é {} e ele tem {} letras".format(separa[1],len(separa[1]))) 
time.sleep(1)
print("Seu terceiro nome é {} e ele tem {} letras".format(separa[2],len(separa[2]))) 
time.sleep(1)
print("Seu quarto nome é {} e ele tem {} letras".format(separa[3],len(separa[3]))) 
